development:
    adapter: postgresql
    encoding: utf8
    database: furniture_store
    username: postgres
    password: postgres
    host: localhost

test: &test
    adapter: postgresql
    encoding: utf8
    database: furniture_store_test
    username: postgres
    password: postgres
    host: localhost
cucumber:
  <<: *test
